#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "💻 Running pre-commit hook..."

yarn lint ||
(
    echo "🚨 Lint failed.";
    false;
)

yarn check ||
(
    echo "🚨 Svelte check failed.";
    false;
)

echo "✅ All check passed
        Committing..."
