#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# echo "💻 Running pre-commit hook..."

# yarn format ||
# (
#     echo "🚨 Fromat failed.";
#     false;
# )

# yarn lint ||
# (
#     echo "🚨 Lint failed.";
#     false;
# )

# yarn types:check || 
# (
#   echo "🚨 Type check failed.";
#   false;
# )


# echo "✅ All check passed
#         Committing..."
